# Generated by Django 5.2.9 on 2025-12-30 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sample", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="is_active",
            field=models.BooleanField(default=True, help_text="Whether item is active"),
        ),
    ]
