// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { ApiApiFixedCreateCleanNullableData, ApiApiFixedCreateCleanNullableResponses, ApiApiFixedCreateItemData, ApiApiFixedCreateItemResponses, ApiApiFixedGetAllRequiredData, ApiApiFixedGetAllRequiredResponses, ApiApiFixedGetProfileData, ApiApiFixedGetProfileResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Create Item
 *
 * CORRECT pattern: Different schemas for request and response.
 * - CreateItemRequest: fields with defaults are optional (can omit)
 * - ItemResponse: all fields are required (always present)
 */
export const apiApiFixedCreateItem = <ThrowOnError extends boolean = false>(options: Options<ApiApiFixedCreateItemData, ThrowOnError>) => (options.client ?? client).post<ApiApiFixedCreateItemResponses, unknown, ThrowOnError>({
    url: '/api-fixed/items',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get All Required
 *
 * Response with all fields forced to required.
 */
export const apiApiFixedGetAllRequired = <ThrowOnError extends boolean = false>(options?: Options<ApiApiFixedGetAllRequiredData, ThrowOnError>) => (options?.client ?? client).get<ApiApiFixedGetAllRequiredResponses, unknown, ThrowOnError>({ url: '/api-fixed/all-required', ...options });

/**
 * Create Clean Nullable
 *
 * Clean nullable field handling.
 */
export const apiApiFixedCreateCleanNullable = <ThrowOnError extends boolean = false>(options: Options<ApiApiFixedCreateCleanNullableData, ThrowOnError>) => (options.client ?? client).post<ApiApiFixedCreateCleanNullableResponses, unknown, ThrowOnError>({
    url: '/api-fixed/clean-nullable',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get Profile
 *
 * Using ResponseBase for automatic required fields.
 */
export const apiApiFixedGetProfile = <ThrowOnError extends boolean = false>(options: Options<ApiApiFixedGetProfileData, ThrowOnError>) => (options.client ?? client).get<ApiApiFixedGetProfileResponses, unknown, ThrowOnError>({ url: '/api-fixed/profile/{user_id}', ...options });
