// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: string;
};

/**
 * ItemResponse
 *
 * RESPONSE schema - NO defaults, all fields are always present.
 * TypeScript: all fields should be required (no `?`).
 */
export type ItemResponse = {
    /**
     * Id
     */
    id: number;
    /**
     * Name
     */
    name: string;
    /**
     * Count
     */
    count: number;
    /**
     * Is Active
     */
    is_active: boolean;
    priority: Priority;
    /**
     * Metadata
     */
    metadata: string | null;
};

/**
 * Priority
 */
export type Priority = 'low' | 'medium' | 'high';

/**
 * CreateItemRequest
 *
 * REQUEST schema - defaults are appropriate here.
 * Fields with defaults CAN be omitted by the client.
 * TypeScript: `field?: type` is CORRECT here.
 */
export type CreateItemRequest = {
    /**
     * Name
     */
    name: string;
    /**
     * Count
     */
    count?: number;
    /**
     * Is Active
     */
    is_active?: boolean;
    priority?: Priority;
    /**
     * Metadata
     */
    metadata?: string | null;
};

/**
 * AllRequiredResponse
 *
 * Force all fields to be required using model_config.
 * This fixes the 'default makes it optional' problem.
 */
export type AllRequiredResponse = {
    /**
     * Name
     */
    name: string;
    /**
     * Count
     */
    count: number;
    /**
     * Is Active
     */
    is_active: boolean;
};

/**
 * CleanNullableSchema
 *
 * Use ONLY `| None` for nullable fields, NOT Optional.
 * And be explicit about whether the field is required.
 */
export type CleanNullableSchema = {
    /**
     * Required Nullable
     */
    required_nullable: string | null;
    /**
     * Required Non Null
     */
    required_non_null: string;
    /**
     * Optional Nullable
     */
    optional_nullable: string | null;
};

/**
 * UserProfileResponse
 *
 * All fields will be required in OpenAPI schema.
 */
export type UserProfileResponse = {
    /**
     * Id
     */
    id: number;
    /**
     * Username
     */
    username: string;
    /**
     * Email
     */
    email: string;
    /**
     * Avatar Url
     */
    avatar_url: string | null;
    /**
     * Created At
     */
    created_at: string;
};

export type ApiApiFixedCreateItemData = {
    body: CreateItemRequest;
    path?: never;
    query?: never;
    url: '/api-fixed/items';
};

export type ApiApiFixedCreateItemResponses = {
    /**
     * OK
     */
    200: ItemResponse;
};

export type ApiApiFixedCreateItemResponse = ApiApiFixedCreateItemResponses[keyof ApiApiFixedCreateItemResponses];

export type ApiApiFixedGetAllRequiredData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api-fixed/all-required';
};

export type ApiApiFixedGetAllRequiredResponses = {
    /**
     * OK
     */
    200: AllRequiredResponse;
};

export type ApiApiFixedGetAllRequiredResponse = ApiApiFixedGetAllRequiredResponses[keyof ApiApiFixedGetAllRequiredResponses];

export type ApiApiFixedCreateCleanNullableData = {
    body: CleanNullableSchema;
    path?: never;
    query?: never;
    url: '/api-fixed/clean-nullable';
};

export type ApiApiFixedCreateCleanNullableResponses = {
    /**
     * OK
     */
    200: CleanNullableSchema;
};

export type ApiApiFixedCreateCleanNullableResponse = ApiApiFixedCreateCleanNullableResponses[keyof ApiApiFixedCreateCleanNullableResponses];

export type ApiApiFixedGetProfileData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: number;
    };
    query?: never;
    url: '/api-fixed/profile/{user_id}';
};

export type ApiApiFixedGetProfileResponses = {
    /**
     * OK
     */
    200: UserProfileResponse;
};

export type ApiApiFixedGetProfileResponse = ApiApiFixedGetProfileResponses[keyof ApiApiFixedGetProfileResponses];
