// This file is auto-generated by @hey-api/openapi-ts

export type AddressSchema = {
    street: string;
    city: string;
    country?: string;
    postal_code?: string;
};

/**
 * Realistic user creation request.
 */
export type CreateUserRequest = {
    username: string;
    /**
     * Valid email address
     */
    email: string;
    password: string;
    age?: number;
    display_name?: string;
    bio?: string;
    /**
     * Personal website URL
     */
    website?: string;
    status?: (Status);
    preferred_status?: Status;
    address?: AddressSchema;
};

/**
 * Fields with default_factory equivalents.
 */
export type DefaultFactorySchema = {
    name: string;
    tags?: Array<(string)>;
    metadata?: {
        [key: string]: unknown;
    };
    scores?: Array<(number)>;
    config?: {
        [key: string]: unknown;
    };
};

/**
 * Fields with default values - should be optional in requests.
 */
export type DefaultValueFieldsSchema = {
    name: string;
    count?: number;
    is_enabled?: boolean;
    description?: string;
};

/**
 * Testing Field() descriptor patterns.
 */
export type FieldDescriptorSchema = {
    name: string;
    /**
     * User's email address
     */
    email: string;
    age?: number;
    /**
     * ISO country code
     */
    country?: string;
    /**
     * User role
     */
    role?: string;
};

/**
 * Filter parameters with various optional patterns.
 */
export type FilterParams = {
    search?: string;
    status?: Status;
    min_date?: string;
    max_date?: string;
    include_inactive?: boolean;
};

/**
 * Create request - some fields optional with defaults.
 */
export type ItemCreateRequest = {
    name: string;
    description?: string;
    price: number;
    quantity?: number;
    is_available?: boolean;
    category_id?: number;
};

/**
 * Response - all fields populated.
 */
export type ItemResponse = {
    id: number;
    name: string;
    description: string;
    price: number;
    quantity: number;
    is_available: boolean;
    category_id: number;
    created_at: string;
};

/**
 * Update request - all fields optional for partial updates.
 */
export type ItemUpdateRequest = {
    name?: string;
    description?: string;
    price?: number;
    quantity?: number;
    is_available?: boolean;
    category_id?: number;
};

/**
 * Testing literal type handling.
 */
export type LiteralTypesSchema = {
    sort_direction?: 'asc' | 'desc';
    priority: 1 | 2 | 3;
    optional_priority?: 1 | 2 | 3;
};

export type sort_direction = 'asc' | 'desc';

export type priority = 1 | 2 | 3;

export type optional_priority = 1 | 2 | 3;

/**
 * A realistic mix of patterns.
 */
export type MixedPatternsSchema = {
    id: number;
    name: string;
    parent_id: number;
    external_ref: number;
    page?: number;
    limit?: number;
    sort_order?: string;
    filter_name?: string;
    search_query?: string;
    default_status?: string;
};

/**
 * Testing nested schema handling.
 */
export type NestedSchema = {
    name: string;
    primary_address: AddressSchema;
    billing_address?: AddressSchema;
    other_addresses?: Array<AddressSchema>;
};

/**
 * Fields that can be None but are still required in input.
 */
export type OptionalFieldsSchema = {
    name: string;
    nickname: string;
    middle_name: string;
};

/**
 * Optional fields with None as default - most permissive.
 */
export type OptionalWithNoneDefaultSchema = {
    name: string;
    nickname?: string;
    bio?: string;
    avatar_url?: string;
};

/**
 * Optional fields but with non-None defaults.
 */
export type OptionalWithValueDefaultSchema = {
    name: string;
    nickname?: string;
    status?: string;
};

/**
 * Typical pagination query params.
 */
export type PaginationParams = {
    page?: number;
    page_size?: number;
    sort_by?: string;
    sort_order?: 'asc' | 'desc';
};

export type sort_order = 'asc' | 'desc';

/**
 * All fields are required with no defaults.
 */
export type RequiredFieldsSchema = {
    name: string;
    age: number;
    email: string;
    is_active: boolean;
};

export type Status = 'active' | 'inactive' | 'pending';

/**
 * Testing what should be 'required but can be null' vs 'optional and can be null'.
 *
 * In Pydantic:
 * - Optional[T] without default = required in input, can be None
 * - Optional[T] = None = not required, can be None
 */
export type StrictOptionalSchema = {
    nullable_required: string;
    nullable_optional?: string;
    required: string;
    optional_with_default?: string;
};

/**
 * Testing Union type handling.
 */
export type UnionTypesSchema = {
    id: (number | string);
    metadata: {
        [key: string]: unknown;
    };
    value: (number | string);
    tag?: string;
};

/**
 * User response with computed/readonly fields.
 */
export type UserResponse = {
    id: number;
    username: string;
    email: string;
    display_name: string;
    bio: string;
    status: Status;
    created_at: string;
    updated_at?: string;
};

export type TestapiApiCreateRequiredFieldsData = {
    body: RequiredFieldsSchema;
};

export type TestapiApiCreateRequiredFieldsResponse = (RequiredFieldsSchema);

export type TestapiApiCreateRequiredFieldsError = unknown;

export type TestapiApiCreateOptionalFieldsData = {
    body: OptionalFieldsSchema;
};

export type TestapiApiCreateOptionalFieldsResponse = (OptionalFieldsSchema);

export type TestapiApiCreateOptionalFieldsError = unknown;

export type TestapiApiCreateDefaultValueFieldsData = {
    body: DefaultValueFieldsSchema;
};

export type TestapiApiCreateDefaultValueFieldsResponse = (DefaultValueFieldsSchema);

export type TestapiApiCreateDefaultValueFieldsError = unknown;

export type TestapiApiCreateOptionalNoneDefaultData = {
    body: OptionalWithNoneDefaultSchema;
};

export type TestapiApiCreateOptionalNoneDefaultResponse = (OptionalWithNoneDefaultSchema);

export type TestapiApiCreateOptionalNoneDefaultError = unknown;

export type TestapiApiCreateOptionalValueDefaultData = {
    body: OptionalWithValueDefaultSchema;
};

export type TestapiApiCreateOptionalValueDefaultResponse = (OptionalWithValueDefaultSchema);

export type TestapiApiCreateOptionalValueDefaultError = unknown;

export type TestapiApiCreateMixedPatternsData = {
    body: MixedPatternsSchema;
};

export type TestapiApiCreateMixedPatternsResponse = (MixedPatternsSchema);

export type TestapiApiCreateMixedPatternsError = unknown;

export type TestapiApiCreateFieldDescriptorsData = {
    body: FieldDescriptorSchema;
};

export type TestapiApiCreateFieldDescriptorsResponse = (FieldDescriptorSchema);

export type TestapiApiCreateFieldDescriptorsError = unknown;

export type TestapiApiCreateUnionTypesData = {
    body: UnionTypesSchema;
};

export type TestapiApiCreateUnionTypesResponse = (UnionTypesSchema);

export type TestapiApiCreateUnionTypesError = unknown;

export type TestapiApiCreateNestedData = {
    body: NestedSchema;
};

export type TestapiApiCreateNestedResponse = (NestedSchema);

export type TestapiApiCreateNestedError = unknown;

export type TestapiApiCreateUserData = {
    body: CreateUserRequest;
};

export type TestapiApiCreateUserResponse = (UserResponse);

export type TestapiApiCreateUserError = unknown;

export type TestapiApiGetUserData = {
    path: {
        user_id: number;
    };
};

export type TestapiApiGetUserResponse = (UserResponse);

export type TestapiApiGetUserError = unknown;

export type TestapiApiCreateItemData = {
    body: ItemCreateRequest;
};

export type TestapiApiCreateItemResponse = (ItemResponse);

export type TestapiApiCreateItemError = unknown;

export type TestapiApiListItemsResponse = (Array<ItemResponse>);

export type TestapiApiListItemsError = unknown;

export type TestapiApiUpdateItemData = {
    body: ItemUpdateRequest;
    path: {
        item_id: number;
    };
};

export type TestapiApiUpdateItemResponse = (ItemResponse);

export type TestapiApiUpdateItemError = unknown;

export type TestapiApiCreateLiteralTypesData = {
    body: LiteralTypesSchema;
};

export type TestapiApiCreateLiteralTypesResponse = (LiteralTypesSchema);

export type TestapiApiCreateLiteralTypesError = unknown;

export type TestapiApiCreateDefaultFactoryData = {
    body: DefaultFactorySchema;
};

export type TestapiApiCreateDefaultFactoryResponse = (DefaultFactorySchema);

export type TestapiApiCreateDefaultFactoryError = unknown;

export type TestapiApiListPaginatedItemsData = {
    query?: {
        include_inactive?: boolean;
        max_date?: (string | null);
        min_date?: (string | null);
        page?: number;
        page_size?: number;
        search?: (string | null);
        sort_by?: (string | null);
        sort_order?: 'asc' | 'desc';
        status?: (Status | null);
    };
};

export type TestapiApiListPaginatedItemsResponse = (Array<ItemResponse>);

export type TestapiApiListPaginatedItemsError = unknown;

export type TestapiApiCreateStrictOptionalData = {
    body: StrictOptionalSchema;
};

export type TestapiApiCreateStrictOptionalResponse = (StrictOptionalSchema);

export type TestapiApiCreateStrictOptionalError = unknown;

export type TestapiApiPathTestData = {
    path: {
        required_id: number;
    };
    query?: {
        default_param?: number;
        optional_param?: (string | null);
    };
};

export type TestapiApiPathTestResponse = (unknown);

export type TestapiApiPathTestError = unknown;

export type TestapiApiQueryTestData = {
    query: {
        nullable?: (string | null);
        optional_nullable?: (string | null);
        required: string;
        with_default?: number;
    };
};

export type TestapiApiQueryTestResponse = (unknown);

export type TestapiApiQueryTestError = unknown;